stages:
  - test
  - build
  - deploy

.test-app:
  stage: test
  image: node:lts-alpine
  script:
    - npm install

.electron-release-build:
  only:
    - master
  stage: build
  image: electronuserland/builder:wine
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/electron-release/*.exe*
      - build/electron-release/*.yml
    expire_in: 1 month

electron-release-deploy:
  only:
    - master
  stage: deploy
  image: electronuserland/builder:wine
  script:
    - npm install
    - npm run deploy
  when: manual